---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-queues.scheduling.queue-scheduler.imliuda.github.com
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - scheduling.queue-scheduler.imliuda.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - queues
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /valiadate-v1alpha1-queues.scheduling.queue-scheduler.imliuda.github.com
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - scheduling.queue-scheduler.imliuda.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - queues
  sideEffects: None
