//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 imliuda.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HierarchyQueueArgs) DeepCopyInto(out *HierarchyQueueArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.WebHook = in.WebHook
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HierarchyQueueArgs.
func (in *HierarchyQueueArgs) DeepCopy() *HierarchyQueueArgs {
	if in == nil {
		return nil
	}
	out := new(HierarchyQueueArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HierarchyQueueArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebHook) DeepCopyInto(out *WebHook) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebHook.
func (in *WebHook) DeepCopy() *WebHook {
	if in == nil {
		return nil
	}
	out := new(WebHook)
	in.DeepCopyInto(out)
	return out
}
